spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/print-ease
    username: admin
    password: Admin@123

#  spring.jpa.properties.javax.persistence.schema-generation.scripts.action
#  spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=schema.sql
#  spring.jpa.properties.hibernate.format_sql=true

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      format-sql: true
      type: info
      use-sql-comments: true
      properties:
        hibernate.use_sql_comments: true
        hibernate.format_sql: true
    properties:
#      javax.persistence.schema-generation.scripts.action: create-drop
#      javax.persistence.schema-generation.scripts.create-target: schema.sql
#      javax.persistence.schema-generation.scripts.drop-target: drop.sql
#      javax.persistence.schema-generation.create-source: metadata
#      javax.persistence.schema-generation.drop-source: metadata
#      javax.persistence.schema-generation.format-sql: true
      hibernate:
        format_sql: true

springdoc:
  show-actuator: true
  paths-to-match: /**
  packages-to-scan: com.printease.application

management:
  endpoint:
    health:
      show-details: ALWAYS
    endpoints:
      web:
        exposure:
          include: "*"


jwt:
  secretKey: secret
  issuer: www.printease.com
  expirationMinute: 120

