spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/print-ease
    username: admin
    password: Admin@123

printEase:
  app:
    jwtSecret: BJAMbHq+BKi4BjAq7O2lDEUNtAfgF9cwqRj8lC9LLbf1mfwOG5NBSC4xbo4GfPDkkw0ZY1RWSwNQInLzIsT0l2n+KQHQZzRImJKLVUsDTIfCwg1j+CUfAWK9oC2SNUkxnqsxFND6Rkc1bIO2xO99A+WpYfxwVFpIWcQWEutpnvqLMCd3w4A04QYT3rOaXj8c3lYUKfEV8bB7kPrAPoUjrKUSzX08zdxDzj4mmw==
    jwtExpirationSeconds: 1296000
    refreshExpiryDays: 30

